"""Anonymous Cloudflare WARP registration.

WARP's free tier needs no account, no email and no payment. A client posts a
WireGuard public key to Cloudflare's device API and gets back a peer, an
endpoint and an address to use: a standard WireGuard tunnel that any
wg-quick can bring up. So vpnctl registers a device itself rather than
requiring the Cloudflare desktop client, which on macOS is a cask that needs
an admin password to install.

What Cloudflare is told: a freshly generated public key, a random install id,
the string "PC" as a model name, and a locale. No name, no email, no machine
identifier. The private key never leaves this machine.

The registration is cached under the config directory because re-registering
on every connect would both be rude and lose the device's assigned address.

There is no third-party dependency here: httpx is already required, and the
keypair is generated by the wireguard-tools that bringing a tunnel up needs
anyway.
"""

from __future__ import annotations

import json
import os
import secrets
import shutil
import stat
import subprocess
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

import httpx

# The API is versioned in its path, and it is strict about it: an older
# version string plus a missing client-version header is answered with
# 429 Too Many Requests rather than an explanatory error, which is what makes
# stale WARP clients look rate limited.
_API_BASE = "https://api.cloudflareclient.com/v0a2158"
_CLIENT_VERSION = "a-6.30-3596"
_USER_AGENT = "okhttp/3.12.1"

# Cloudflare's own client uses 1280, which leaves room for the WireGuard
# header inside a 1500 byte path without relying on fragmentation.
WARP_MTU = 1280

_TIMEOUT = 20.0


class WarpError(RuntimeError):
    """Registration or activation failed."""


@dataclass
class WarpDevice:
    """Everything needed to build a WireGuard config, plus the device's id."""

    device_id: str
    token: str
    private_key: str
    public_key: str
    address_v4: str
    address_v6: str
    peer_public_key: str
    endpoint_host: str
    endpoint_v4: str
    ports: list[int] = field(default_factory=lambda: [2408])

    @property
    def port(self) -> int:
        """The UDP port to dial.

        The API reports the anycast addresses with port 0 and lists the real
        ports separately, so reading endpoint.v4 straight out of the response
        yields an unusable "162.159.192.2:0".
        """
        return self.ports[0] if self.ports else 2408

    def interface_address(self) -> str:
        """The client address with a prefix, which the API omits."""
        if not self.address_v4:
            return ""
        return self.address_v4 if "/" in self.address_v4 else f"{self.address_v4}/32"

    def endpoint(self, *, prefer_host: bool = True) -> str:
        """The peer address for a WireGuard config.

        The hostname is preferred because Cloudflare moves the anycast
        addresses around, but wg-quick resolves it once at setup time, so a
        caller without working DNS can ask for the literal instead.
        """
        if prefer_host and self.endpoint_host:
            _, _, port = self.endpoint_host.rpartition(":")
            return self.endpoint_host if port.isdigit() else f"{self.endpoint_host}:{self.port}"
        literal = self.endpoint_v4.rpartition(":")[0] or self.endpoint_v4
        return f"{literal}:{self.port}"


def _headers(token: Optional[str] = None) -> dict[str, str]:
    headers = {
        "Content-Type": "application/json",
        "CF-Client-Version": _CLIENT_VERSION,
        "User-Agent": _USER_AGENT,
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers


def generate_keypair() -> tuple[str, str]:
    """Return (private, public), generated by wg.

    wireguard-tools is already required to bring a tunnel up, so leaning on
    it here avoids pulling in a curve25519 implementation for one operation.
    """
    if not shutil.which("wg"):
        raise WarpError(
            "wg not found, so a WireGuard keypair cannot be generated. "
            "Install: brew install wireguard-tools"
        )
    private = subprocess.run(
        ["wg", "genkey"], capture_output=True, text=True, check=True
    ).stdout.strip()
    public = subprocess.run(
        ["wg", "pubkey"], input=private, capture_output=True, text=True, check=True
    ).stdout.strip()
    return private, public


def _post_registration(public_key: str, client: httpx.Client) -> dict[str, Any]:
    install_id = secrets.token_urlsafe(8)[:11]
    body = {
        "key": public_key,
        "install_id": install_id,
        "fcm_token": "",
        "tos": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z"),
        "model": "PC",
        "serial_number": install_id,
        "locale": "en_US",
    }
    response = client.post(f"{_API_BASE}/reg", json=body, headers=_headers())
    if response.status_code == 429:
        raise WarpError(
            "Cloudflare answered 429 to the registration. That is usually the "
            "API version being stale rather than real rate limiting, but it "
            "can also mean too many registrations from this address. Waiting "
            "and retrying is the only remedy."
        )
    if response.status_code >= 400:
        raise WarpError(
            f"WARP registration failed with HTTP {response.status_code}: "
            f"{response.text[:200]}"
        )
    return response.json()


def _activate(device_id: str, token: str, client: httpx.Client) -> None:
    """Turn WARP on for the device.

    Registering alone is not enough: the device exists but the tunnel stays
    inert, which presents as a WireGuard interface that comes up and then
    never completes a handshake.
    """
    response = client.patch(
        f"{_API_BASE}/reg/{device_id}",
        json={"warp_enabled": True},
        headers=_headers(token),
    )
    if response.status_code >= 400:
        raise WarpError(
            f"WARP device registered but could not be enabled (HTTP "
            f"{response.status_code}): {response.text[:200]}"
        )


def register() -> WarpDevice:
    """Register an anonymous free device and return its tunnel parameters."""
    private_key, public_key = generate_keypair()

    with httpx.Client(timeout=_TIMEOUT) as client:
        payload = _post_registration(public_key, client)

        device_id = payload.get("id") or ""
        token = payload.get("token") or ""
        config = payload.get("config") or {}
        peers = config.get("peers") or []
        if not device_id or not token or not peers:
            raise WarpError(
                "WARP registration returned an unexpected shape: "
                f"{sorted(payload)}"
            )

        _activate(device_id, token, client)

    peer = peers[0]
    endpoint = peer.get("endpoint") or {}
    addresses = (config.get("interface") or {}).get("addresses") or {}

    return WarpDevice(
        device_id=device_id,
        token=token,
        private_key=private_key,
        public_key=public_key,
        address_v4=addresses.get("v4", ""),
        address_v6=addresses.get("v6", ""),
        peer_public_key=peer.get("public_key", ""),
        endpoint_host=endpoint.get("host", ""),
        endpoint_v4=endpoint.get("v4", ""),
        ports=[int(p) for p in endpoint.get("ports") or [2408]],
    )


def device_path(config_dir: Optional[Path] = None) -> Path:
    base = config_dir or (Path.home() / ".config" / "vpnctl")
    return base / "warp-device.json"


def save(device: WarpDevice, path: Optional[Path] = None) -> Path:
    """Write the device out at 0600.

    The file holds a private key and a bearer token, so it is created with
    restrictive permissions rather than chmod-ed afterwards: a world readable
    window, however brief, is still a window.
    """
    target = path or device_path()
    target.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(target, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as handle:
        json.dump(asdict(device), handle, indent=2)
    return target


def load(path: Optional[Path] = None) -> Optional[WarpDevice]:
    """Read a cached device, or None if there is not one to read."""
    target = path or device_path()
    if not target.exists():
        return None

    mode = stat.S_IMODE(target.stat().st_mode)
    if mode & 0o077:
        raise WarpError(
            f"{target} holds a private key but is readable by others "
            f"({oct(mode)}). Run: chmod 600 {target}"
        )

    try:
        raw = json.loads(target.read_text())
        return WarpDevice(**raw)
    except (json.JSONDecodeError, TypeError) as exc:
        raise WarpError(
            f"{target} is not a usable WARP device file ({exc}). "
            "Delete it and vpnctl will register a new one."
        ) from exc


def load_or_register(path: Optional[Path] = None) -> WarpDevice:
    """Return the cached device, registering one the first time."""
    existing = load(path)
    if existing is not None:
        return existing
    device = register()
    save(device, path)
    return device
